[2018-11-14 01:11:47,545] worker_client_logger INFO:state_file_syncher started.
[2018-11-14 01:11:47,545] worker_client_logger INFO:STATE_SYNCHER: Connected to 0.0.0.0:7777.
[2018-11-14 01:11:47,545] worker_client_logger INFO:EVALLOG_RECVER: Socket starts at 0.0.0.0:6666
[2018-11-14 01:11:47,545] worker_client_logger INFO:eval_log_file_receiver started.
[2018-11-14 01:11:47,545] worker_client_logger INFO:Listening...
[2018-11-14 01:11:47,548] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 103, in _state_file_syncher
    recv_json = json.loads(recv_str)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2018-11-14 01:11:52,554] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:11:57,561] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:02,567] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:07,573] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:12,578] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:17,583] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:22,589] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:27,591] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:32,597] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:37,603] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:42,609] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:47,612] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:52,619] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:12:57,624] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:02,627] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:07,633] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:12,640] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:17,642] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:22,647] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:27,653] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:32,658] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:37,660] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:42,666] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:47,672] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:52,677] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:13:57,684] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:02,690] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:07,695] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:12,701] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:17,706] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:22,709] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:27,711] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:32,717] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:37,723] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:42,729] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:47,731] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:52,737] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:14:57,743] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:02,744] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:07,750] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:12,755] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:17,759] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:22,765] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:27,771] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:32,776] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:37,782] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:42,788] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:47,791] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:52,797] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:15:57,804] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:02,810] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:07,815] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:12,821] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:17,827] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:22,834] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:27,840] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:32,846] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:37,852] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:42,858] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:47,864] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:52,870] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:16:57,875] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:02,881] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:07,887] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:12,893] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:17,900] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:22,907] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:27,913] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:32,920] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:37,927] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:42,933] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:47,935] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:52,941] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:17:57,948] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:02,955] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:07,961] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:12,967] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:17,973] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:22,978] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:27,983] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:32,989] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:37,997] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:43,004] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:48,011] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:53,017] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:18:58,024] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:03,027] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:08,030] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:13,036] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:18,043] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:23,047] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:28,053] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:33,059] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:38,062] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:43,068] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:48,071] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:53,077] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:19:58,082] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:20:03,087] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:20:08,093] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:20:13,099] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:20:18,105] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:20:23,107] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:20:28,111] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:20:33,117] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 01:20:38,123] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

