[2018-11-14 05:22:20,914] worker_client_logger INFO:state_file_syncher started.
[2018-11-14 05:22:20,915] worker_client_logger INFO:eval_log_file_receiver started.
[2018-11-14 05:22:20,915] worker_client_logger INFO:EVALLOG_RECVER: Socket starts at 0.0.0.0:6666
[2018-11-14 05:22:20,915] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:22:20,915] worker_client_logger INFO:Listening...
[2018-11-14 05:22:25,922] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:22:30,928] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:22:35,934] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:22:40,941] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:22:45,947] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:22:50,954] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:22:55,958] worker_client_logger INFO:STATE_SYNCHER: Connected to 0.0.0.0:7777.
[2018-11-14 05:22:55,959] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 102, in _state_file_syncher
    recv_str = s.recv(4096).decode(encoding = 'utf-8');
ConnectionResetError: [Errno 104] Connection reset by peer

[2018-11-14 05:23:00,965] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:05,971] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:10,977] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:15,984] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:20,990] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:25,994] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:31,001] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:36,007] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:41,011] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:46,017] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:51,024] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:56,031] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

