[2018-11-14 05:23:58,546] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:23:58,546] worker_client_logger INFO:state_file_syncher started.
[2018-11-14 05:23:58,546] worker_client_logger INFO:EVALLOG_RECVER: Socket starts at 0.0.0.0:6666
[2018-11-14 05:23:58,546] worker_client_logger INFO:Listening...
[2018-11-14 05:23:58,547] worker_client_logger INFO:eval_log_file_receiver started.
[2018-11-14 05:24:03,552] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:24:08,559] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:24:13,565] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

[2018-11-14 05:24:18,572] worker_client_logger INFO:STATE_SYNCHER: Connected to 0.0.0.0:7777.
[2018-11-14 05:24:18,574] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 102, in _state_file_syncher
    recv_str = s.recv(4096).decode(encoding = 'utf-8');
ConnectionResetError: [Errno 104] Connection reset by peer

[2018-11-14 05:24:23,582] worker_client_logger INFO:STATE_SYNCHER: ERROR: Traceback (most recent call last):
  File "/home/zhiangz/Documents/HVAC-RL-Control/src/HVAC_RL_web_worker_client/web_worker_server.py", line 99, in _state_file_syncher
    s.connect((ip_this, int(port_this)));
ConnectionRefusedError: [Errno 111] Connection refused

